# syntax=docker/dockerfile:1
FROM debian:10

RUN apt-get -y update && apt-get install -y vim mc python3 python3-pip

# COPY ./hello.php /var/www/html/index.php

# CMD ["/usr/sbin/httpd","-D","FOREGROUND"]

EXPOSE 80
