apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: azCluster
  region: eu-central-1

nodeGroups:
  - name: az-1
    instanceType: t3.micro
    desiredCapacity: 2
    volumeSize: 80
#    ssh:
#      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: az-2
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 50
